# Generated by Django 4.2.4 on 2023-08-10 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='itemLocation',
            new_name='userLocation',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='itemName',
            new_name='userName',
        ),
    ]
