# Generated by Django 4.2.4 on 2023-08-10 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_location_locationname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='locationName',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userLocation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.location'),
        ),
    ]
