# Generated by Django 4.2.4 on 2023-08-10 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_location_locationname_alter_user_userlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userLocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location'),
        ),
    ]
