# Generated by Django 4.2.4 on 2023-08-12 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('UserID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Username', models.CharField(max_length=100)),
                ('date_added', models.DateField(auto_now=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('password', models.TextField()),
            ],
        ),
    ]
